### ISSUE TITLE
Definition, listing 2.3

### ISSUE THREAD

**Issue by FerusAndBeyond** [carl24k/fight-churn#19]
In listing 2.3 activity churn is calculated. But this isn't exactly according to the stated definition. Take this example:
a = activity
--Month 1 --Month 2
|a--------|||--------a|

If a user has activity in the beginning of the start period and then nothing until the end of the end period, it will have past more than the period considered inactive (1 month). But the user is not considered churned. I guess it sort of makes sense since the user is active again, but this listing doesn't really fulfill the definition.

**Comment by carl24k** [comment]
Thanks for the helpful comment! I think if you ran the calculation in the middle of month 2, you would find the customer churned. Right? But it is true if someone churned and then came back within the month, and you ran the calc at the end of the month, you would miss the fact that they were temporarily classified as churned. Actually this is also true of termed subscriptions, if someone lapses to churn but then signs up again within the period you use to calculate churn you would miss them. So now I am trying to think of if there is another way to do this that makes more sense... Will comment again here if I think of anything.

**Comment by FerusAndBeyond** [comment]
Yes subscription also I suppose. Perhaps one could save in "start_accounts" the last activity in the first month and in "end_accounts" the first activity in the second month and then, as an additional or-condition for churn, check if the difference between these two dates exceeds the inactivity-interval.

**Comment by carl24k** [comment]
There's a similar situation for paid subscriptions: Suppose you measure churn at the end of every month, and a user cancels early in the month, but resigns up before you measure churn at the end of the month. The churn calculation would not calculate them, because they resigned up at the end of the month. Its the same as the user activity based measurement you described, right? I think this is generally an edge case with churn measurement, but its not really significant. It is related to the discussion of time period selection in chapter 2: https://livebook.manning.com/book/fighting-churn-with-data/chapter-2/399. In principle, the way to catch every single churn even if they resign up is to measure daily churn and scale the results to monthly or annual. Same thing for catching customers who go inactive for just the minimum length of time: You will have to measure churn every single day. Then you could average your results over many days. Does that suggestion help?
